#!/bin/bash

set -e

# how many check_http's can we do we at once?
if [ -z "$n" ]
then
  n=16
fi

if [ -z "$cycle_time" ]
then
  cycle_time=3
fi

while true
do
  xargs -P $n -I{} ./check_http {} < sites.txt
  sleep $cycle_time
done
